---
name: Tests

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: tests-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: lts/*
      - run: npm ci
      - run: npm run test
